### ISSUE TITLE
Doc updates

### ISSUE THREAD

**Issue by bbkane** [luisalvesmartins/Markdown-Mermaid-Expand-to-PNG#1]
Could you please put a link to the VS Code extension ( https://marketplace.visualstudio.com/items?itemName=LuisAlvesMartins.markdown-code-to-png ) somewhere.

Also, please make it clear that this extension depends on  HTTP requests to a 3rd party server ( mermaid.ink ) to run. Unfortunately, that means I can't use this for my company projects ... I'm sure it's possible to extract the logic from https://github.com/jihchi/mermaid.ink , but not sure if that's something you think would be useful

**Comment by luisalvesmartins** [comment]
Thank you bbkane. Will do.
