### ISSUE TITLE
Trailling "]" at the end of img link

### ISSUE THREAD

**Issue by Iziram** [luisalvesmartins/Markdown-Mermaid-Expand-to-PNG#3]
As title says, there is a trailling "]" at the end of the image link `[block](image.png)]<------`
Your extension is really usefull but that thing annoys me.

**Comment by luisalvesmartins** [comment]
Thanks for reporting this. Fixed! 
Can you please verify?

**Comment by Iziram** [comment]
Should work fine ( I looked at the code ) 
I'll wait till the version is published on the marketplace to test it.

Thanks

EDIT: 

Works great
